language: php
php:
- 7.1
- 7.2
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=latest
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh cwp_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ptEXukfiPvrXyeXsZrA57C0lcIr7unclkKCZTw5uBlftIphTjMMZb8TmcEqlal7MQfAncGvrZMZ4kXmYTI1ruESrLOA3U1pFY3MhHhYshpNifQ8P6QIByksuW1ueJPWPSRBrQpXkbJ5WCzpmxd4tL2jYmefGtf9gV67NH5+nxNPVf7lSjn7YfO17C2O9MQ8Qxkxk4Sk6aXhzLl6KAQu2zju1J1NnGY5hBkdcw1rbBv7u9BDRDiBnzVBQwrv/wQ27jT5ZCOSDITMaGvjUU2daVaKcHjTdu/ivAEpsUDe8jiD5oCMMseWsuNDZiXdPRpSub1n5U3AzH/3+XaNd3I/V9tviKz+bf+wuepvr1zKadeB4Xw5+gmPMWW8VCAXDoGS4uR+kHJgQsGaAmT0SJmxvjVZ+PVU76suDYt2XZkjZj64ASmkpePqUuS0GmF/FvjmlBFdegBvoYL/JMAcsNmtcASI3+q7pV5/aJvjWpLiTNuoCJjSOF8pZ/HX7hTN0NPkJUivFEtk8Qiul4fvEDRWm2nrbaxSE5iIIzkHwxdLR5rO9i0hp36tXm6gUPJvd8BOq7hdHVRzF7MZeDpw3RRZa999VxptZ0cl210EQLcEBJrdhpp351aZbJwkhqkathbkNKtKgk9RuAw2dFgC+XYh5LMqJAzV2wLa3KVjeFsLqMlo=
  file: custom-wp-notify-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/custom-wp-notify
    branch: dev
